#!/usr/bin/env bash
set -euo pipefail

cd /root/workspace/Self-Forcing

CAUSAL_WAN_LOCAL_ATTN_SIZE=27
INCREMENTAL_KV_CONTEXT_NOISE=1
SELF_CONDITIONING_LOOKAHEAD_CHUNKS=2
SELF_CONDITIONING_ANCHOR_POLICY=random_valid
SELF_CONDITIONING_MIX_RATIO=0.25
SELF_CONDITIONING_CONSISTENCY_WEIGHT=0.0
SELF_CONDITIONING_LOSS_ON=all_predicted_chunks
SELF_CONDITIONING_INTERMEDIATE_LOSS_WEIGHT=0.5

# train_ar_draft_head.py commits only the attention-visible prefix suffix for
# incremental KV replay. With 9 blocks x 3-frame chunks and local_attn_size=27,
# the last chunk can see the full 24-frame prefix plus its own 3 frames.
for TEACHER_TRAJECTORY_OBJECTIVE in incremental_kv_flow hybrid_prefix_incremental_kv_flow stop_gradient_self_conditioning_flow; do
  if [[ "$TEACHER_TRAJECTORY_OBJECTIVE" == "hybrid_prefix_incremental_kv_flow" ]]; then
    TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT=0.25
    TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT=1.0
  else
    TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT=0.0
    TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT=1.0
  fi

  echo "Launching $TEACHER_TRAJECTORY_OBJECTIVE with local_attn_size=$CAUSAL_WAN_LOCAL_ATTN_SIZE context_noise=$INCREMENTAL_KV_CONTEXT_NOISE"

  env \
  PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
  TORCH_DISTRIBUTED_TIMEOUT_SECONDS=3600 \
  TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=3600 \
  NCCL_TIMEOUT=3600 \
  WAN_FLASH_ATTN_VERSION=2 \
  WAN_ATTENTION_BACKEND=flash \
  CAUSAL_WAN_FLEX_COMPILE_MODE=none \
  CHECKPOINT_ROOT=/mnt/lanxiangh/checkpoints/specgen \
  HEAD_TYPE=causal_wan_ar \
  TRAINING_MODE=teacher_trajectory \
  TEACHER_TRAJECTORY_OBJECTIVE="$TEACHER_TRAJECTORY_OBJECTIVE" \
  TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT="$TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT" \
  TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT="$TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT" \
  TEACHER_TRAJECTORY_STEP_MODE=sample_one \
  TEACHER_TRAJECTORY_STEP_INDICES="0 1 2 3" \
  MANIFEST_PATH=/mnt/lanxiangh/data/ff_exec/ar_teacher_trajectory_cache/krea14b_unipc5_shift8_20260621_223429/manifest.json \
  INIT_TARGET_MODEL_NAME=Wan2.1-T2V-1.3B \
  INIT_TARGET_CHECKPOINT_PATH=/mnt/lanxiangh/models/Self-Forcing/checkpoints/self_forcing_dmd.pt \
  INCREMENTAL_KV_CONSISTENCY_WEIGHT=0.0 \
  INCREMENTAL_KV_CONTEXT_NOISE="$INCREMENTAL_KV_CONTEXT_NOISE" \
  SELF_CONDITIONING_LOOKAHEAD_CHUNKS="$SELF_CONDITIONING_LOOKAHEAD_CHUNKS" \
  SELF_CONDITIONING_ANCHOR_POLICY="$SELF_CONDITIONING_ANCHOR_POLICY" \
  SELF_CONDITIONING_MIX_RATIO="$SELF_CONDITIONING_MIX_RATIO" \
  SELF_CONDITIONING_CONSISTENCY_WEIGHT="$SELF_CONDITIONING_CONSISTENCY_WEIGHT" \
  SELF_CONDITIONING_LOSS_ON="$SELF_CONDITIONING_LOSS_ON" \
  SELF_CONDITIONING_INTERMEDIATE_LOSS_WEIGHT="$SELF_CONDITIONING_INTERMEDIATE_LOSS_WEIGHT" \
  PREDICTION_TYPE=flow \
  LOSS_TYPE=flow \
  FLOW_LOSS_WEIGHT=1.0 \
  CLEAN_LATENT_LOSS_WEIGHT=0.0 \
  DMD_LOSS_WEIGHT=0.0 \
  DENOISING_STEP_LIST="999 969 922 841 666" \
  TIMESTEP_SHIFT=8.0 \
  CAUSAL_WAN_LOCAL_ATTN_SIZE="$CAUSAL_WAN_LOCAL_ATTN_SIZE" \
  CAUSAL_WAN_SINK_SIZE=0 \
  CAUSAL_WAN_PREFIX_PADDING=none \
  BATCH_SIZE=1 \
  NUM_GPUS=8 \
  EPOCHS=5 \
  LR=2e-5 \
  MAX_GRAD_NORM=0.5 \
  SKIP_NONFINITE_GRAD=1 \
  PARAM_FINITE_CHECK_EVERY=0 \
  DEBUG_TIMING_STEPS=1 \
  DEBUG_TIMING_ALL_RANKS=1 \
  DEBUG_NONFINITE_BACKWARD=0 \
  AMP_DTYPE=none \
  FSDP_MIXED_PRECISION=none \
  FSDP_MIN_NUM_PARAMS=10000000 \
  GRADIENT_CHECKPOINTING=1 \
  PARALLEL_STRATEGY=fsdp \
  VAL_FRACTION=0.0 \
  MODEL_ROOT=/mnt/lanxiangh/models \
  CONFIG_PATH=/root/workspace/Self-Forcing/configs/self_forcing_dmd.yaml \
  bash launch_scripts/draft_head/train_draft_head_clean_latent_mse+flow.sh
done
