#!/usr/bin/env bash
set -euo pipefail

cd /root/workspace/Self-Forcing

# Match the old all-span 20260623 run as closely as possible, but train the
# fast incremental-KV path instead of the prefix teacher-forcing path.
CAUSAL_WAN_LOCAL_ATTN_SIZE=-1
INCREMENTAL_KV_CONTEXT_NOISE=1

TEACHER_TRAJECTORY_OBJECTIVE=incremental_kv_flow
TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT=0.0
TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT=1.0

echo "Launching $TEACHER_TRAJECTORY_OBJECTIVE with old allspan settings local_attn_size=$CAUSAL_WAN_LOCAL_ATTN_SIZE context_noise=$INCREMENTAL_KV_CONTEXT_NOISE"

env \
  PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
  TORCH_DISTRIBUTED_TIMEOUT_SECONDS=3600 \
  TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=3600 \
  NCCL_TIMEOUT=3600 \
  WAN_FLASH_ATTN_VERSION=2 \
  WAN_ATTENTION_BACKEND=flash \
  CAUSAL_WAN_FLEX_COMPILE_MODE=default \
  CHECKPOINT_ROOT=/mnt/lanxiangh/checkpoints/specgen \
  HEAD_TYPE=causal_wan_ar \
  TRAINING_MODE=teacher_trajectory \
  TEACHER_TRAJECTORY_OBJECTIVE="$TEACHER_TRAJECTORY_OBJECTIVE" \
  TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT="$TEACHER_TRAJECTORY_PREFIX_LOSS_WEIGHT" \
  TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT="$TEACHER_TRAJECTORY_INCREMENTAL_KV_LOSS_WEIGHT" \
  TEACHER_TRAJECTORY_STEP_MODE=whole_graph \
  TEACHER_TRAJECTORY_STEP_INDICES="" \
  MANIFEST_PATH=/mnt/lanxiangh/data/ff_exec/ar_teacher_trajectory_cache/krea14b_unipc5_shift8_20260621_223429/manifest.json \
  INIT_TARGET_MODEL_NAME=Wan2.1-T2V-1.3B \
  INIT_TARGET_CHECKPOINT_PATH=/mnt/lanxiangh/models/Self-Forcing/checkpoints/self_forcing_dmd.pt \
  INCREMENTAL_KV_CONSISTENCY_WEIGHT=0.0 \
  INCREMENTAL_KV_CONTEXT_NOISE="$INCREMENTAL_KV_CONTEXT_NOISE" \
  PREDICTION_TYPE=flow \
  LOSS_TYPE=flow \
  FLOW_LOSS_WEIGHT=1.0 \
  CLEAN_LATENT_LOSS_WEIGHT=0.0 \
  DMD_LOSS_WEIGHT=0.0 \
  DENOISING_STEP_LIST="999 969 922 841 666" \
  TIMESTEP_SHIFT=8.0 \
  CAUSAL_WAN_LOCAL_ATTN_SIZE="$CAUSAL_WAN_LOCAL_ATTN_SIZE" \
  CAUSAL_WAN_SINK_SIZE=0 \
  CAUSAL_WAN_PREFIX_PADDING=full \
  BATCH_SIZE=1 \
  NUM_GPUS=8 \
  EPOCHS=3 \
  LR=1e-6 \
  MAX_GRAD_NORM=1.0 \
  SKIP_NONFINITE_GRAD=1 \
  PARAM_FINITE_CHECK_EVERY=1 \
  DEBUG_TIMING_STEPS=0 \
  DEBUG_TIMING_ALL_RANKS=0 \
  DEBUG_NONFINITE_BACKWARD=0 \
  AMP_DTYPE=bf16 \
  FSDP_MIXED_PRECISION=none \
  FSDP_MIN_NUM_PARAMS=100000000 \
  GRADIENT_CHECKPOINTING=1 \
  PARALLEL_STRATEGY=fsdp \
  VAL_FRACTION=0.0 \
  MODEL_ROOT=/mnt/lanxiangh/models \
  CONFIG_PATH=/root/workspace/Self-Forcing/configs/self_forcing_dmd.yaml \
  bash launch_scripts/draft_head/train_draft_head_clean_latent_mse+flow.sh
